# This is a basic workflow to help you get started with Actions

name: add_latest_follower

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'
  push:
    branches: '*'
  pull_request:
    branches: '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: 🐍 Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: 📥 Install Packages
      script: pip install tweepy
    
    - name: add-latest-follower
      script: python scripts/add_latest_follower.py
      with:
        env:
          CONSUMER_KEY:${{ secrets.TWITTER_CONSUMER_KEY }}
          CONSUMER_SECRET:${{ secrets.TWITTER_CONSUMER_SECRET }}
          ACCESS_TOKEN:${{ secrets.TWITTER_ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET:${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: README.md
        commit_message: Add Latest Follower
        commit_user_name: Follower Bot
        commit_user_email: follower-bot@waylonwalker.com
        commit_author: Follower Bot <follower-bot@waylonwalker.com>

